lipanski/mockito

Cargo.toml
According to the changelog on Hyper non of the breaking changes should
cause issues with this crate.
https://github.com/hyperium/hyper/blob/v0.10.4/CHANGELOG.md#breaking-changes-1
=> Bump hyper version to 0.10.0

Cargo.toml, src/lib.rs, src/server.rs
I'm interested in adding support for users to match mocks based on the request body. This PR makes that a little bit easier. Are you interested in that feature?
=> Change usage of rustc_serialize to serde

src/lib.rs
Currently, Mockito binds its server to 0.0.0.0, which exposed the server to every host on the network. This _probably_ isn't the correct behavior. It also generated several annoying firewall popups per test 
run on my machine (using the default macOS firewall settings, AFAIK).
This PR changes the server to run on 127.0.0.1, so it's not accessible to other machines.
=> Don't expose server to the network

src/lib.rs, src/server.rs, tests/lib.rs
I came across some intermittent test failures when working on some code that serializes HTTP responses. This seemed like it should be deterministic, so this was very surprising.
It turned out that the problem came from Mockito using a `HashMap` to store response headers. Switching this to an array, and explcitly specifying a static `Date` header, should be enough to make Mockito responses entirely deterministic, which is especially desirable in a library focused on testing.
=> Preserve response header order

src/request.rs, src/server.rs, tests/lib.rs
Hello!
It's me again )
Sorry about noise from me, but I'm have `Utf8Error` issue when mock response with utf8 files around 200-500K. 
Bug was on code:
```
self.body.push_str(str::from_utf8(value).unwrap());
```
Where `value` is 1024 length buffer of `u8` wich can contain not valid utf8 string (truncated if source utf8 string large then 1024 bytes) and on `unwrap` mocking server panics with  `Utf8Error`
Solution is:
- gather full request body to `Vec<u8>` from read buffer
- deserilize raw request body from slice directly and don't panic on some error
=> don't panic about Utf8Error on large utf8 body

src/server.rs
Hello!
It's me again.
In my test all mocks are unique and I want run tests without `--test-threads=1`
```
$ cargo test --all
...
running 3 tests
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 98, message: "Address already in use" } }', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 98, message: "Address already in use" } }', /checkout/src/libcore/result.rs:860:4
test test_1... ok
test test_2 ... ok
test test_3 ... ok
```
With this PR  tests runs without noise about paniced threads.
```
$ cargo test --all
...
running 3 tests                    
test test_1 ... ok                              …
```
=> bind server address once

src/request.rs, src/server.rs
Prevents the following warnings at compile time:
```
warning: variable does not need to be mutable                                                                                                                                                        
--> src/server.rs:120:14                                                                                                                                                                          
|                                                                                                                                                                                                
120 |         Some(mut mock) => { …
```
=> remove useless mut keywords in order to prevent compilation warnings

.appveyor.yml, .travis.yml, README.md, src/lib.rs, tests/lib.rs
...by ensuring internally that tests creating mocks run sequentially.
A simpler, less intrusive alternative to https://github.com/lipanski/mockito/pull/34
=> Remove the need for --test-threads=1

src/lib.rs, tests/lib.rs
…but break creating mocks from within sub-threads.
=> Remove the test function name condition

src/lib.rs, src/server.rs, tests/lib.rs
Allows combining of matchers into "one or the other" expression.
Implements `PartialEq` on `Option<&str>` instead of `String`, which removes need to check for `Missing` separately.
=> 'Or' Matcher

src/lib.rs, src/request.rs, src/server.rs, tests/lib.rs
The `Via` header supports multiple values only as separate headers, so to test it, it's necessary to support multiple values per header.
At this point matching with `PartialEq` was getting too wild, so I've just changed it to a regular method.
=> Multivalued headers

src/request.rs
When running tests using mockito in win-64, incoming requests frequently parse as `<unknown>` for some reason. To allow our tests to run and pass in win-64, we would like to be able to match `<unknown>`, but that is not currently possible because the mocked method is converted to uppercase (in `Mock::new()`).
This PR converts the incoming request to uppercase, so that `<unknown>` --> `<UNKNOWN>`, and we can match against it.
=> Uppercase the incoming request method

tests/files/simple.http, tests/lib.rs
I dunno why there were no tests for this feature and also why simple.http was provided with a status line considering the feature being about bodies only. So I decided to change this it.
=> Add missed test for bodies read from files

.travis.yml, src/request.rs
This adds a compatibility `use` statement so that `mockito` can be successfully built on slightly older toolchains, and adds a travis check for that (arbitrary minimum version: 1.29.0).
=> lib: keep compatibility with older toolchains

src/lib.rs, src/server.rs
Busy-looping `while !is_listening() {}` wasn't very nice. 
Additionally, it'd say `true` when the port was used by another application, which lead to misleading test failures.
=> Precise listening notification

benches/lib.rs, src/lib.rs, src/server.rs, tests/lib.rs
This change makes mockito use a random free port assigned by the operating system.
The upside is that the port number won't conflict with any application, including other test processes that might be running in parallel.
The downside is that it's no longer possible to have `SERVER_ADDRESS` as a constant. It has to be a function call, so it's a breaking change.
=> Use auto-assigned port

src/request.rs, tests/lib.rs
While investigating issue #60, I found that at times not the entire request body is read after one `stream.read` call. I noticed that from time to time code was reading only 123 bytes out of 125. Remaining 2 bytes were making request body JSON impossible to parse which has resulted into the error that I've reported in comments for #60.
I also noticed that current implementation does not allow reading requests that are longer than 1024 bytes. I've tried to address it.
Another issue that I found is that even parser status is `httparse::Status::Complete`, it does not mean that entire body was read already. It should be fixed in proposed PR as well. 
It is tricky to automate testing of scenario when not entire request is read in one take, since it's random. Instead I've added a test that …
=> Fix request parsing (fixes #60)

src/request.rs, src/server.rs, tests/lib.rs
* Propagate the version of HTTP protocol to a response.
* Handle large bodies without "Content-Length" (HTTP/1.0).
=> Support HTTP/1.0 and working without Content-Length

src/lib.rs, tests/lib.rs
=> Matcher::AllOf

src/lib.rs, src/request.rs, src/response.rs, src/server.rs, tests/lib.rs
=> Allow generating response programmatically

Cargo.toml, src/diff.rs, src/lib.rs
This allows one to use  this crate without bringing in the pretty big `colored` crate dependency and for when colored text diffs are not important.
The new `color` feature flag is enabled by default so no change in the default behavior
=> Move colored diff output to feature flag

Cargo.toml, src/lib.rs, src/request.rs, src/response.rs, src/server.rs
I have just done the minimum steps outlined in the [Edition guide](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#updating-your-code-to-be-compatible-with-the-new-edition) without edition idiom migration
=> use the Rust 2018 edition

benches/lib.rs, examples/mockito-server.rs, src/diff.rs, src/lib.rs, src/request.rs, src/response.rs, src/server.rs, tests/lib.rs
I noticed that you did some formatting changes in 3b519bb.
To make it easier for contributors to adhere to a common style, would you be willing to use `cargo fmt`?
This would also make the code more consistent with other codebases using the same tool.
=> Fix some edition idioms and run cargo fmt

src/lib.rs, tests/lib.rs
Add functions `expect_at_least` and `expect_at_most` as described in issue #79.
=> add support for at_least and at_most

Cargo.toml
Also `^` in Cargo doesn't do anything (it's the default behavior)
=> Bump dependency

src/lib.rs
Hi. We are using your library in our project https://github.com/tg-rs/tg-rs 
But suddenly found that CI can't pass tests.
```
error[E0432]: unresolved imports `assert_json_diff::Actual`, `assert_json_diff::Comparison`, `assert_json_diff::Expected`
--> /home/vladimir/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.23.1/src/lib.rs:565:46
|
565 | use assert_json_diff::{assert_json_no_panic, Actual, Comparison, Expected};
|                                              ^^^^^^  ^^^^^^^^^^  ^^^^^^^^ no `Expected` in the root
|                                              |       |
|                                              |       no `Comparison` in the root
|                                              no `Actual` in the root
error[E0061]: this function takes 3 parameters but 1 …
```
=> Update assert-json-diff version.

Cargo.toml, src/lib.rs, tests/lib.rs
=> Warnings on missing .create()

src/server.rs, tests/lib.rs
This is an implementation proposal of the feature previously discussed in issue #97.
The idea is to detect if there is multiple mock matching the same request and calling them while the number of request expected is not reached. When it is reached we call the next one. If there is no more available we keep calling the last one.
=> Proposal: multiple mock matching

src/lib.rs
Fortunately, rust provides raw strings literals r#"..."#
which makes writing json literals very easy.
Also, I think doc strings and mocking examples should be tested as well. Just in case.
=> Fix json in docs

src/lib.rs, tests/lib.rs
Hi! First off, thanks so much for the library - it's been *_super_* useful to me across several projects!
I was struggling with a test that had an `AllOf` match that wasn't matching, and in the error output I was getting:
```
> Expected 1 request(s) to:
GET /path?(all of)
accept: (any)
host: (any)
```
I thought it might be useful to be able to actually see all of the queries that were expected to match.
In doing so, I refactored the `Display` logic a bit to reduce some of what I thought were duplications.
There are tests that demonstrate the new output, but in summary, it looks like:
```
> Expected 1 request(s) to:
GET /path?(query1, query2 (regex), key3=val3 (urlencoded)) (all of)
accept: (any)
host: (any)
```
It seemed to follow the precedence and I'd be happy to make any changes to it. …
=> Improve Matcher display

Cargo.toml, src/lib.rs, tests/lib.rs
This is a fix that resolves #121 and also comes with a slightly leaner implementation of `Matcher::UrlEncoded`'s match arm in `Matcher::matches_value`
Open to any feedback / suggestions!
=> fix: use serde_urlencoded for query matching

src/lib.rs, tests/lib.rs
Hi!
Thanks so much for this library - I really appreciate the work you've put into it! I have a slightly unusual use case surrounding testing async processing and I'd basically like to check to see if the mock has matched while not panicking. It looks like `mockito::mock` isn't `UnwindSafe` so catching the `assert` panic requires wrapping it in a `AssertUnwindSafe` which I'm not totally sure is correct.
This just provides a `matched` method that returns a bool for this particular use case. Let me know what you think/if it's appropriate or not!
Thanks!!!
=> Add a matched() -> bool method to mock

src/lib.rs, src/request.rs, src/response.rs
Hi, this is the second option to fix linting issues arisen in #128. This is **alternative** to #129.
A great shout out to @wolf4ood that concoted this solution. The details are in the last commit message, but the juice is the choice to compare only a part of the BodyFn bear by the `Body::Fn` variant.
=> Fix clippy, option 2

Cargo.toml, src/lib.rs
I recently released assert-json-diff 2.0.0 which had [a few breaking changes](https://github.com/davidpdrsn/assert-json-diff/blob/main/CHANGELOG.md#200---2021-01-23).
=> Update assert-json-diff to 2.0.0

Cargo.toml, src/diff.rs, tests/lib.rs
Replace difference library with similar because difference is no longer
maintained. See advisory: https://rustsec.org/advisories/RUSTSEC-2020-0095
Updated related tests due to slightly different diffing output.
Fixes #132
=> Replace difference library with similar

src/request.rs, tests/lib.rs
When httpparse fails to parse a request, it will return an error. For instance when a header is invalid, httparse will return error `Error::HeaderName`.
The current logic was to mark the error and re-enter the loop. When this happens, the buffer may be empty and the test will block indefinitely.
This change marks the request as `parsed` when httparse returns an error parsing the content so this can be returned back to the client.
=> Handle httpparse error

Cargo.toml, src/command.rs, src/error.rs, src/lib.rs, src/mock.rs, src/server.rs, src/server_pool.rs, tests/lib.rs
Related to https://github.com/lipanski/mockito/issues/155 and https://github.com/lipanski/mockito/issues/157
- Use reqwest in tests
- Replace std:net::TcpListener with tokio::net::TcpListener
- Make sure oneshot senders don't get dropped before receiving
- Small refactoring in Mock::assert to avoid calling hits twice
- Stream with while not with loop
- Expose a ServerGuard object which dereferences to Server
-  When recycling servers, check if the sender & state are still busy
- Disable server pool for now
=> Various fixes

src/lib.rs
This example is still using `mockito::mock` instead of creating a `Server`, i guess this was an oversight when changing all the examples.
=> Don't use outdated function in lib.rs example

src/mock.rs, src/server.rs, src/server_pool.rs, tests/lib.rs
Closes https://github.com/lipanski/mockito/issues/166
This MR replaces the tokio Mutexes/RwLocks with the sync Mutex/RwLock which is [preferred](https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html) as long as the sync Mutex is not held across `await` calls.
Since the server state is now wrapped in a sync Mutex, there's no need to call `block_on` inside the `Drop` implementations any more.
It also replaces the tokio oneshot channel that shares the server port with a sync mpsc channel. This was the cause for the server pool blocking on `futures::future::join_all`.
=> Replace tokio Mutexes with sync Mutexes

src/server.rs, src/server_pool.rs, tests/lib.rs
Closes https://github.com/lipanski/mockito/issues/171
=> Implement created counter on the server pool properly and lower the pool size

src/response.rs, src/server.rs, tests/lib.rs
=> Support streaming body

.github/workflows/linters.yml, .github/workflows/tests.yml, Cargo.toml, README.md, src/server_pool.rs, tests/lib.rs
=> Simplify server pool

src/matcher.rs, src/mock.rs, src/request.rs, src/response.rs, src/server.rs, tests/lib.rs
This uses the `http` types `HeaderMap`, `HeaderName` and `HeaderValue` where appropriate, instead of `Vec<(String, String)>`. This disallows invalid header names at the call site.
This is a breaking change, because the functions `Mock::match_header` and `Mock::with_header` no longer accept `&str`. They will accept `&'static str` however.
=> Use HeaderMap for headers in mock and response

src/error.rs, src/lib.rs, src/mock.rs, tests/lib.rs
Related to https://github.com/lipanski/mockito/pull/179 and the alternative to https://github.com/lipanski/mockito/pull/180
=> Introduce a local IntoHeaderName trait to avoid exposing hyper::header::HeaderName

tests/lib.rs
This fixes the clippy warnings.
Also, false positive clippy warning for `vec_init_then_push` has been fixed.
=> Use async mutex for tests

src/server.rs
I have a lambda function that would be nice to end-to-end test. It functions as a proxy and receives a URL, resolves it to an IP address and then returns the response to the client. The existing tests use `mockito` for the HTTP responses and point directly to the server, but it would be good to test the DNS resolution in the mix as well.
In essence, it would be nice to do something like:
```rust
let host = "example.com";
let mut http_server = mockito::Server::new();
let mut dns_server = dns_mock_server::Server::new();
let socket_addr = http_server.socket_address();
dns_server.add_records(host, vec![socket_addr.ip()]);
let port = socket_addr.port();
let uri = format!("http://{host}:{port}");
handle_request(uri);
```
This will then resolve `example.com` into the address of the `mockito` …
=> feat: return raw socket address

Cargo.toml, src/response.rs, src/server.rs
Uses the `tokio` runtime which is used in the other APIs.
=> Use tokio runtime uniformly

.github/workflows/linters.yml, .github/workflows/tests.yml, Cargo.toml, README.md
=> Revert colored crate version pinning

Cargo.toml, src/response.rs, src/server.rs
=> Refactor response body

src/mock.rs, src/response.rs, src/server.rs, tests/lib.rs
=> Add with_header_from_request function

src/matcher.rs, src/mock.rs
Removes the unnecessary imports.
=> Remove unnecessary import
